### ISSUE TITLE
Golden images failing

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#707] opened 2023-08-16 11:38 UTC
Seems like something in the environment has changed for us, these two builds are essentially of the same code but the one I ran now is failing:

Failing: https://github.com/AmbientRun/Ambient/actions/runs/5877174640/job/15937292565?pr=705
Passing (older): https://github.com/AmbientRun/Ambient/actions/runs/5834341472/job/15824363335

Things to check:
- [ ] Is there any difference in the logs (I checked briefly the first part and machine etc. are the same)
- [ ] Is bevy/wgpu running into this as well?

**Comment by Pombal** [comment] 2023-08-16 12:32
The only relevant difference in the failing build log is the addition of --mute-audio, which is not present in the working build.

`./ambient run --release guest/rust/examples/basics/input --headless --no-proxy --quic-interface-port 9000 --http-interface-port 10000 --mute-audio golden-image-check --timeout-seconds 30.0`

**Comment by Pombal** [comment] 2023-08-17 22:59
This issue was caused by incompatible drivers because of `add-apt-repository ppa:oibaf/graphics-drivers -y`

Fixed with https://github.com/AmbientRun/Ambient/commit/26c12221dc2f5b4012d10ecb6c2dac0cb3a86633

**Closed by Pombal** 2023-08-17 22:59 UTC
Labels: bug
