### ISSUE TITLE
Calling many despawn() results in segfault

### ISSUE THREAD

**Issue by saikyun** [AmbientRun/Ambient#296] opened 2023-04-12 13:31 UTC
Hello! I created a little program based off of the physics example. I wanted to despawn cubes after a while. Doing this a lot resulted in a segfault: `zsh: segmentation fault  ambient run`

Here's the code:

```
use std::{collections::HashSet, iter::Map};

use ambient_api::{
    components::core::{
        ecs::ids,
        game_objects::player_camera,
        physics::{
            angular_velocity, box_collider, dynamic, linear_velocity, physics_controlled,
            visualizing,
        },
        prefab::prefab_from_url,
        primitives::cube,
        rendering::{cast_shadows, color},
        transform::{lookat_center, rotation, scale, translation},
    },
    concepts::{make_perspective_infinite_reverse_camera, make_transformable},
    entity::set_components,
    physics::raycast,
    prelude::*,
};

#[main]
pub async fn main() -> EventResult {
    Entity::new()
        .with_merge(make_perspective_infinite_reverse_camera())
        .with_default(player_camera())
        .with(translation(), vec3(5., 5., 4.))
        .with(lookat_center(), vec3(0., 0., 4.))
        .spawn();

    Entity::new()
        .with_merge(make_transformable())
        .with(prefab_from_url(), asset_url("assets/Shape.glb").unwrap())
        .spawn();

    let q = ambient_api::ecs::GeneralQuery::create(components::despawn_timer());
    let b = q.build();

    b.each_frame(|data| {
        for (id, v) in data {
            if v <= 0.0 {
                entity::despawn(id);
            } else {
                entity::set_components(
                    id,
                    Entity::new().with(components::despawn_timer(), v - 0.01),
                );
            }
        }
    });

    loop {
        Entity::new()
            .with_merge(make_transformable())
            .with_default(cube())
            .with_default(visualizing())
            .with(box_collider(), Vec3::ONE)
            .with(dynamic(), true)
            .with_default(physics_controlled())
            .with_default(cast_shadows())
            .with(translation(), vec3(0., 0., 5.))
            .with(scale(), vec3(0.5, 0.5, 0.5))
            .with(color(), Vec4::ONE)
            .with(components::despawn_timer(), random::<f32>() * 0.5 + 0.1)
            .spawn();

        sleep(0.01).await;
    }
}
```

abmient.toml:
```
[project]
id = "physics"
name = "Physics"
version = "0.0.1"

[components.despawn_timer]
type = "F32"
name = "Despawn Timer"
description = "Die."
attributes = ["Networked", "Debuggable"]
```

**Comment by philpax** [comment] 2023-04-12 19:26
Looked into this and determined the cause is with the WASM collision event, which attempts to get the shapes on a presumably-deleted PhysX ref:
https://github.com/AmbientRun/Ambient/blob/2ecad4a93a6b3c7b0f31b455d290d3d221103f9b/crates/wasm/src/shared/mod.rs#L129-L154

`collisions` is updated through the simulation event callbacks:

https://github.com/AmbientRun/Ambient/blob/2ecad4a93a6b3c7b0f31b455d290d3d221103f9b/crates/wasm/src/shared/mod.rs#L129-L154

Assigning this to Fredrik as I'm not sure what the best fix would be here. It seems like it should be one of two things:

1) Store the `EntityId`s in `collisions()` after fetching them in the collision callback (is there any concern about validity or performance in doing this?)
2) Extend the lifetime of the ref (which appears to be a pointer with no kind of lifetime enforcement or safety?)

**Comment by FredrikNoren** [comment] 2023-04-13 06:49
Hm yeah I think 1. is the way to go. I don't think there's any way to extend the ref lifetimes (it's just a pointer to a C++ object, and once it's deleted it's gone). I'll see if I can make a fix

**Comment by FredrikNoren** [comment] 2023-04-13 07:06
I verified with the example that it worked as well

**Closed** 2023-04-13 07:05 UTC
Labels: bug
