### ISSUE TITLE
Address misuse of log and tracing verbosity levels

### ISSUE THREAD

**Issue by ten3roberts** [AmbientRun/Ambient#584] opened 2023-07-18 10:36 UTC
We currently mainly use the `info` levels and above for our logging directives. This has resulted in a lot of verbose terminal output, which we have fixed by conditionally reducing log levels by injecting extra directives.

This is not the intended usage of logs and env filtering. The extra steps we take to crate-by-crate silence the info log level is very rough and leads to a *very* inconsistent behavior, and makes it difficult to conditionally enable some extra logging for a crate you are trying to debug. It is not possible because there is no way to distinguish the lower level chatty logs from the general high level logs since they are all *log::info*.

Setting a specific log level using `RUST_LOG` often does not lead to the intended result, and more often than not leads to a complete flood of logs since we don't distinguish them.

The solution to this is *not* to add more fine grained *silencing* but rather make proper use of the log levels. This way, we can also add *debug* or even *trace* level logs that are very chatty but can be kept in the source and enabled explicitly (rather than *unsilence* through a combination of a complicated directives in an env string"). If a bug is encountered in a crate the crate or even module can be surgically targeted for `trace` directives to be enabled, without leading to unexpected walls of texts from other logs that surface.

Additionally, the current method makes logging inconsistent when a function crosses a crate boundary via a helper function and your logs suddenly dispensary.

What do you think about this @philpax

**Comment by ten3roberts** [comment] 2023-07-18 10:47
I may add that on the web, there is no env filtering, since there is no environment variables.

This means that the only way to filter logs is through chrome's `verbosity` checkbox in the console.

Our current situation means it is a boolean of *all logs* or *nothing*, and makes it incredibly unwieldy to use.

**Comment by philpax** [comment] 2023-07-31 08:14
I think this might be a dupe of #459. When you have some free time, would you be interested in fixing this up and closing both issues?

**Comment by philpax** [comment] 2023-07-31 08:26
I'd say they're both addressing the user problem of "there are too many logs", but I'm not too fussed. We can address both at the same time. (Perhaps #459 is better linked to #564)?

**Comment by ten3roberts** [comment] 2023-07-31 11:13
Yes we could. #584 is a *solution* to the end-user problem defined by #459, while #564 aids our development experience after #584

**Closed** 2023-10-12 11:58 UTC
Labels: meta:help wanted, topic:web, topic:maintenance
