### ISSUE TITLE
My package works locally, but not when deployed

### ISSUE THREAD

**Issue by droqen** [AmbientRun/Ambient#741] opened 2023-08-23 17:28 UTC
@pierd recommended starting to use `deploy` more often for our projects, so I'm trying to get in the habit of doing so. Not sure what the status of Windows Chrome web builds is.

Here's the deploy link I'm using: https://ambient-733e7.web.app/packages/mover_this

I see this:
![image](https://github.com/AmbientRun/Ambient/assets/5104632/78d4d5f0-3579-4bd7-9051-66b3acb3f534)

I get a _lot_ of stuff in the console, but I believe this is the one that it's attempting to display:
```
ambient_network::web::client: Game failed: No such component: 336
```

The package source is here:
https://github.com/droqen/23-08Blue/tree/main/03_packthis/mover_this

**Comment by philpax** [comment] 2023-08-23 17:34
This is likely due to the lack of clientside WASM support - can you temporarily disable your clientside WASM (remove the bin from Cargo.toml, then do a clean build, then redeploy) and report back?

**Comment by droqen** [comment] 2023-08-23 17:40
Yes, that seems to stop that error from occurring @philpax. So I'll stay off the deploys until I get the word clientside WASM is working?

**Comment by philpax** [comment] 2023-08-23 17:45
Feel free to deploy - it just might not work with the web client right now. You can also use deploys for two other things:
- server hosting (ensure-running - you might need to dig around for how this works, I'm not near the codebase right now)
- sharing your project for others with the native client to play

That is, you should be able to do `ambient run the_deployment_url`. You can't do that yet with packages with dependencies, but I should have that ready very soon.

**Comment by droqen** [comment] 2023-08-23 17:53
`ambient run the_deployment_url` does not appear to work. I'm using the url `https://assets.ambient.run/7FkP5H4n5F0ivc1IqQmUZd`, and I am just getting a black screen.

**Comment by philpax** [comment] 2023-08-23 18:30
🤔 

Yeah I can reproduce it, will look into it tomorrow - probably related to our troubles yesterday. Just to confirm something - you're on Windows, right?

**Comment by droqen** [comment] 2023-08-23 18:32
Yep, Windows. The package I tested and deployed can be found here: https://github.com/droqen/23-08Blue/tree/main/03_packthis/deploy_test

**Comment by ten3roberts** [comment] 2023-08-24 07:47
Yes

Until #656 is merged client side scripts don't work and spit out an error

**Comment by philpax** [comment] 2023-08-24 09:27
Alrighty, should be fixed - can you update `main` to after https://github.com/AmbientRun/Ambient/commit/e2474f35b24725b2c1dc2e43aee1319f4aca4a41 and see if the same issue still occurs?

**Comment by droqen** [comment] 2023-08-24 18:10
The `ambient run [url]` issue is fixed, my test works :) Will continue to play around with that and see ifa nything new comes up.

**Comment by philpax** [comment] 2023-08-28 13:38
Do you think this can be closed now?

**Closed** 2023-08-29 12:04 UTC
Labels: bug, meta:question, topic:web
