### ISSUE TITLE
Unknown networked component: package_manager::mod_manager_for

### ISSUE THREAD

**Issue by ten3roberts** [AmbientRun/Ambient#950] opened 2023-09-25 10:13 UTC
<img width="2672" alt="image" src="https://github.com/AmbientRun/Ambient/assets/25723553/0cae4bae-65bf-4f1f-a081-91840098811f">

**Comment by philpax** [comment] 2023-09-25 10:15
Dupe of #927; I'll make it clearer that's the root cause of this issue

**Closed by philpax** 2023-09-25 10:15 UTC
Labels: bug, topic:networking, topic:packages
