### ISSUE TITLE
UI align end in examples doesn't work

### ISSUE THREAD

**Issue by chaosprint** [AmbientRun/Ambient#533] opened 2023-06-27 07:31 UTC
<img width="912" alt="image" src="https://github.com/AmbientRun/Ambient/assets/35621141/6ada3a89-a279-4129-88e8-a089bddbf0f4">

**Comment by philpax** [comment] 2023-07-31 08:00
Discovered the cause of this - the components didn't update alignment correctly. I've inadvertently fixed this by reintroducing enums in #417.

Will close this once #417 is merged.

**Closed** 2023-08-11 14:34 UTC
Labels: bug, topic:ui
