### ISSUE TITLE
Allow the retrieving of an entire entity by ID

### ISSUE THREAD

**Issue by marceline-cramer** [AmbientRun/Ambient#517] opened 2023-06-20 21:51 UTC
I'd like to be able to clone entire entities, including components that the cloning code may not be aware of. The purpose is to be able to instantiate entity [prototypes](https://refactoring.guru/design-patterns/prototype) that contain mod-defined components relating to mod-defined behavior.

@philpax mentioned adding an `entity::get_all_components` guest API call that could do this, and this definitely works for my use case, especially since I can look up non-mod components before they are spawned into the world and trigger spawn systems.

This is pretty high-priority because this design pattern will be very common in Flowerpot.

**Comment by philpax** [comment] 2023-06-28 19:57
Dupe of #90, but I'll close both once it's done

**Closed** 2023-06-30 15:06 UTC
Labels: issue:enhancement
