### ISSUE TITLE
Better error messages when ambient versions mismatch

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#526] opened 2023-06-22 06:59 UTC
There are a couple of way that the versions can mismatch:

- [ ] When a client connects to a server
- [ ] When a server tries to run a wasm that was compiled with another api version

Ambient should just stop with an error message in those cases

**Comment by philpax** [comment] 2023-07-31 08:12
This is (now) a dupe of #560 and #206. Closing in favour of those.

**Closed by philpax** 2023-07-31 08:12 UTC
Labels: enhancement, topic:api
